### PR TITLE
MFLT-3720: Rename URLs and links containing "embedded" to MCU and add redirects

### PR DESCRIPTION
**Pull request by fnune**
Redirects:

https://github.com/memfault/memfault-docs/pull/72/files#diff-16b6401519950c5f36e2548e217df9174771c97bbfb0c8ead59906fe108d28feR7-R13

Sitemap diff:

```diff
--- old.xml	2021-06-16 14:54:29.813483658 +0200
+++ new.xml	2021-06-16 14:59:07.033628538 +0200
@@ -226,32 +226,32 @@
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/embed/embedded</loc>
+      <loc>https://docs.memfault.com/embed/mcu</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/embed/embedded/arm-cortex-m-guide</loc>
+      <loc>https://docs.memfault.com/embed/mcu/arm-cortex-m-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/embed/embedded/embedded-self-serve</loc>
+      <loc>https://docs.memfault.com/embed/mcu/embedded-self-serve</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/embed/embedded/esp32-guide</loc>
+      <loc>https://docs.memfault.com/embed/mcu/esp32-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/embed/embedded/esp8266-rtos-sdk-guide</loc>
+      <loc>https://docs.memfault.com/embed/mcu/esp8266-rtos-sdk-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/embed/embedded/nrf-connect-sdk-guide</loc>
+      <loc>https://docs.memfault.com/embed/mcu/nrf-connect-sdk-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
@@ -326,132 +326,132 @@
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/arm-cortex-m-guide</loc>
+      <loc>https://docs.memfault.com/docs/mcu/arm-cortex-m-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/arm-gcc-guide</loc>
+      <loc>https://docs.memfault.com/docs/mcu/arm-gcc-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/arm-gcc-guide-coredumps</loc>
+      <loc>https://docs.memfault.com/docs/mcu/arm-gcc-guide-coredumps</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/arm-iar-guide</loc>
+      <loc>https://docs.memfault.com/docs/mcu/arm-iar-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/arm-mdk-guide</loc>
+      <loc>https://docs.memfault.com/docs/mcu/arm-mdk-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/coredump-elf-with-gdb</loc>
+      <loc>https://docs.memfault.com/docs/mcu/coredump-elf-with-gdb</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/coredumps</loc>
+      <loc>https://docs.memfault.com/docs/mcu/coredumps</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/data-from-firmware-to-the-cloud</loc>
+      <loc>https://docs.memfault.com/docs/mcu/data-from-firmware-to-the-cloud</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/demo-cli</loc>
+      <loc>https://docs.memfault.com/docs/mcu/demo-cli</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/esp32-guide</loc>
+      <loc>https://docs.memfault.com/docs/mcu/esp32-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/esp8266-rtos-sdk-guide</loc>
+      <loc>https://docs.memfault.com/docs/mcu/esp8266-rtos-sdk-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/event-serialization-overview</loc>
+      <loc>https://docs.memfault.com/docs/mcu/event-serialization-overview</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/export-chunks-over-console</loc>
+      <loc>https://docs.memfault.com/docs/mcu/export-chunks-over-console</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/introduction</loc>
+      <loc>https://docs.memfault.com/docs/mcu/introduction</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/logging</loc>
+      <loc>https://docs.memfault.com/docs/mcu/logging</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/metrics-api</loc>
+      <loc>https://docs.memfault.com/docs/mcu/metrics-api</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/nrf-connect-sdk-guide</loc>
+      <loc>https://docs.memfault.com/docs/mcu/nrf-connect-sdk-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/reboot-reason-tracking</loc>
+      <loc>https://docs.memfault.com/docs/mcu/reboot-reason-tracking</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/releases-integration-guide</loc>
+      <loc>https://docs.memfault.com/docs/mcu/releases-integration-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/self-serve</loc>
+      <loc>https://docs.memfault.com/docs/mcu/self-serve</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/self-serve-local-testing</loc>
+      <loc>https://docs.memfault.com/docs/mcu/self-serve-local-testing</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/test-data-collection-with-gdb</loc>
+      <loc>https://docs.memfault.com/docs/mcu/test-data-collection-with-gdb</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/test-patterns-for-chunks-endpoint</loc>
+      <loc>https://docs.memfault.com/docs/mcu/test-patterns-for-chunks-endpoint</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/trace-events</loc>
+      <loc>https://docs.memfault.com/docs/mcu/trace-events</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/uploading-software-versions</loc>
+      <loc>https://docs.memfault.com/docs/mcu/uploading-software-versions</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
    <url>
-      <loc>https://docs.memfault.com/docs/embedded/xilinx-a53-sdk-guide</loc>
+      <loc>https://docs.memfault.com/docs/mcu/xilinx-a53-sdk-guide</loc>
       <changefreq>weekly</changefreq>
       <priority>0.5</priority>
    </url>
```

### CODE REVIEW

**Comment by martijnthe** [comment]
Will you also update the mflt.io _redirects in the monorepo?

**Comment by fnune** [comment]
> Will you also update the mflt.io _redirects in the monorepo?

Will do. I believe they wouldn't break right now thanks to the Netlify redirects included in this PR.

**Comment by fnune** [comment]
@martijnthe https://github.com/memfault/memfault/pull/4162

**Review by martijnthe — APPROVED** [review]

**Review by chrisc11 — APPROVED** [review]
sanity checking, /embedded routes should still work due to redirect?

**Comment by fnune** [comment]
> sanity checking, /embedded routes should still work due to redirect?

https://github.com/memfault/memfault-docs/pull/72/files#diff-16b6401519950c5f36e2548e217df9174771c97bbfb0c8ead59906fe108d28feR9-R13

Yup, unless I got them wrong. I haven't found a way to test Netlify's redirects before deploying :/

**Comment by martijnthe** [comment]
@fnune since Chris already reviewed this one, just go ahead and merge. I'll fix up /rebase https://github.com/memfault/memfault-docs/pull/73.

**Comment by fnune** [comment]
I did get them wrong @chrisc11 :| fixed here https://github.com/memfault/memfault-docs/pull/77

(Already merged)

**Pull request merged**
