### PR TITLE
Document all the AOSP rate limits

### PR DESCRIPTION
**Pull request by martijnthe**
Screenshot from 2021-11-26 09-44-54

### CODE REVIEW

**Review by fnune — APPROVED** [review]
Sweet! THX

Wondering if it's worth adding matching warning in the linked-to docs. For example, for Metrics, we did this:

```md
Apart from being limited by quotas, the ingestion of Metrics may be
[rate-limited](/docs/platform/rate-limiting#custom-reports). Avoid sending data
more than once per hour per device.
```

**Comment by martijnthe** [comment]
> Wondering if it's worth adding matching warning in the linked-to docs.

Added!

**Review by fnune — APPROVED** [review]

**Review by vlindhol — APPROVED** [review]
👍

**Comment by HBehrens** [comment]
It's a nit but I wonder of we should aim for a consistent order when we mention,

1. MCU,
2. Android, and 
3. Embedded Linux.

Our docs use this order in our side bar, albeit the top bar navigation diverges (Android last). Your table seems to use alphabetical order (which would lead to Android, Embedded Linux, MCU) but I would guess that you'd have chosen "All" as the first item regardless…

**Comment by martijnthe** [comment]
@HBehrens will change the order to All, MCU, Android, Linux in a separate PR.

**Pull request merged**
