### PR TITLE
Refresh Subsystem Integration Guides

### PR DESCRIPTION
**Pull request by chrisc11**
With main [getting started guides](https://docs.memfault.com/docs/embedded/arm-cortex-m-guide) now available, the subsystem integration guides are confusing as they repeat steps that would have been implemented as part of the initial port.

I'd like to move the subsystems guides to be an overview of how each subsystem works and how to make the most of it. This PR makes a first pass attempt at that by:

* Subsystem guides now redirect to the basic integration as a pre-requisite
* I've reworked reboot, metrics, trace event guides to focus on how to make use of the module instead of how to integrate it since the integration work is now taken care of in the initial port

### CODE REVIEW

**Comment by mrfirmware** [comment]
I've tried to read through the diffs but it's not like code diffs. Is there a better way to view the changes?

**Comment by chrisc11** [comment]
> I've tried to read through the diffs but it's not like code diffs. Is there a better way to view the changes?

There's a "deploy-preview" generated by CI: https://deploy-preview-42--memfault-docs.netlify.app/

**Comment by mrfirmware** [comment]
Deploy-view is great, thanks.

Notes:
- Looks great, I love it. This documentation is so professional.
- I tried to read it all but I don't know if I caught everything

Nits:
- https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/metrics-api#defining-custom-metrics says "in this file" but the filename is only mention as a comment in the header of the copy text.
- https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/metrics-api#initial-setup--debug-apis the last bullet has a typo "iterval"
- At the same section should we mention the default interval, e.g. The heartbeat interval can be reduced *from the default 3600 seconds* for debug purposes by setting
- https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/logging#5-optional-collect-logs-as-part-of-coredump can we choose to save logs as part of coredump by #define MEMFAULT_COREDUMP_COLLECT_LOG_REGIONS 1 instead of as a CFLAG?
- https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/releases-integration-guide#firmware-integration-checklist I think "there's a few common configuration items" --> "there are a few common...*
- https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/test-data-collection-with-gdb#register-handler maybe point out that memfault_data_export_dump_chunks() must be called in the program for the install_chunk_handler to work (this tripped me up).

**Comment by chrisc11** [comment]
> Deploy-view is great, thanks.
> 
> Notes:
> 
>     * Looks great, I love it. This documentation is so professional.
> 
>     * I tried to read it all but I don't know if I caught everything
> 
> 
> Nits:
> 
>     * https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/metrics-api#defining-custom-metrics says "in this file" but the filename is only mention as a comment in the header of the copy text.
> 
>     * https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/metrics-api#initial-setup--debug-apis the last bullet has a typo "iterval"
> 
>     * At the same section should we mention the default interval, e.g. The heartbeat interval can be reduced _from the default 3600 seconds_ for debug purposes by setting
> 
>     * https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/logging#5-optional-collect-logs-as-part-of-coredump can we choose to save logs as part of coredump by #define MEMFAULT_COREDUMP_COLLECT_LOG_REGIONS 1 instead of as a CFLAG?
> 
>     * https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/releases-integration-guide#firmware-integration-checklist I think "there's a few common configuration items" --> "there are a few common...*
> 
>     * https://deploy-preview-42--memfault-docs.netlify.app/docs/embedded/test-data-collection-with-gdb#register-handler maybe point out that memfault_data_export_dump_chunks() must be called in the program for the install_chunk_handler to work (this tripped me up).

Thanks, incorporated all the suggestions!

**Pull request merged**
